project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Featherlight TTRPG"
  repo-url: https://github.com/njlyon0/featherlight-ttrpg
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right: 
      - icon: github
        href: https://github.com/lter/workshop-quarto
  page-footer: 
    center: "Copyright 2025, Nicholas Lyon"
    background: secondary

format:
  html:
    theme:
      light: _extensions/njlyon0/lyon_theme/lyon_light.scss
      dark: _extensions/njlyon0/lyon_theme/lyon_dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false